export const doctors = [
  {
    id: 1,
    name: "Dr. Sarah Johnson",
    specialty: "Cardiologist",
    image: "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?q=80&w=2070&auto=format&fit=crop",
    rating: 4.9,
    reviews: 124,
    experience: "15+ years",
    education: "Harvard Medical School",
    about: "Dr. Johnson is a board-certified cardiologist specializing in preventive cardiology and heart disease management.",
    availability: ["Mon", "Tue", "Wed", "Fri"],
    nextAvailable: "Today",
    location: "Downtown Medical Center",
    price: 150,
  },
  {
    id: 2,
    name: "Dr. James Chen",
    specialty: "Dermatologist",
    image: "https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?q=80&w=2070&auto=format&fit=crop",
    rating: 4.8,
    reviews: 97,
    experience: "10+ years",
    education: "Johns Hopkins School of Medicine",
    about: "Dr. Chen specializes in medical dermatology, cosmetic procedures, and skin cancer treatment.",
    availability: ["Mon", "Wed", "Thu", "Fri"],
    nextAvailable: "Tomorrow",
    location: "Westside Skin Clinic",
    price: 175,
  },
  {
    id: 3,
    name: "Dr. Amara Patel",
    specialty: "Neurologist",
    image: "https://images.unsplash.com/photo-1594824476967-48c8b964273f?q=80&w=2070&auto=format&fit=crop",
    rating: 4.7,
    reviews: 112,
    experience: "12+ years",
    education: "Stanford University Medical Center",
    about: "Dr. Patel is an expert in treating neurological disorders including migraines, epilepsy, and movement disorders.",
    availability: ["Tue", "Wed", "Thu", "Sat"],
    nextAvailable: "Today",
    location: "Neurology Partners Medical Group",
    price: 200,
  },
  {
    id: 4,
    name: "Dr. Michael Rodriguez",
    specialty: "Orthopedic Surgeon",
    image: "https://images.unsplash.com/photo-1622253692010-333f2da6031d?q=80&w=2070&auto=format&fit=crop",
    rating: 4.9,
    reviews: 156,
    experience: "20+ years",
    education: "Columbia University College of Physicians",
    about: "Dr. Rodriguez specializes in sports medicine and minimally invasive joint replacement surgery.",
    availability: ["Mon", "Tue", "Thu", "Fri"],
    nextAvailable: "Next week",
    location: "Advanced Orthopedic Center",
    price: 225,
  },
  {
    id: 5,
    name: "Dr. Emily Washington",
    specialty: "Pediatrician",
    image: "https://images.unsplash.com/photo-1551601651-2a8555f1a136?q=80&w=2070&auto=format&fit=crop",
    rating: 4.9,
    reviews: 203,
    experience: "8+ years",
    education: "Yale School of Medicine",
    about: "Dr. Washington provides comprehensive healthcare for children from birth through adolescence with a focus on developmental pediatrics.",
    availability: ["Mon", "Wed", "Thu", "Fri", "Sat"],
    nextAvailable: "Today",
    location: "Children's Wellness Center",
    price: 135,
  },
  {
    id: 6,
    name: "Dr. Robert Kim",
    specialty: "Psychiatrist",
    image: "https://images.unsplash.com/photo-1582750433449-648ed127bb54?q=80&w=2070&auto=format&fit=crop",
    rating: 4.6,
    reviews: 78,
    experience: "14+ years",
    education: "NYU School of Medicine",
    about: "Dr. Kim specializes in mood disorders, anxiety, and ADHD management with a holistic approach to mental health.",
    availability: ["Tue", "Wed", "Fri"],
    nextAvailable: "3 days",
    location: "Mindful Psychiatry Associates",
    price: 190,
  },
  {
    id: 7,
    name: "Dr. Olivia Thompson",
    specialty: "Endocrinologist",
    image: "https://images.unsplash.com/photo-1584516297938-039c5beefb5d?q=80&w=2070&auto=format&fit=crop",
    rating: 4.8,
    reviews: 92,
    experience: "11+ years",
    education: "Mayo Clinic School of Medicine",
    about: "Dr. Thompson treats hormonal imbalances and metabolic disorders with particular expertise in diabetes management and thyroid conditions.",
    availability: ["Mon", "Thu", "Fri", "Sat"],
    nextAvailable: "Tomorrow",
    location: "Metabolic & Hormone Specialists",
    price: 165,
  },
  {
    id: 8,
    name: "Dr. Marcus Johnson",
    specialty: "Ophthalmologist",
    image: "https://images.unsplash.com/photo-1537368910025-700350fe46c7?q=80&w=2070&auto=format&fit=crop",
    rating: 4.7,
    reviews: 114,
    experience: "16+ years",
    education: "Baylor College of Medicine",
    about: "Dr. Johnson provides comprehensive eye care including LASIK surgery, cataract treatment, and glaucoma management.",
    availability: ["Mon", "Tue", "Wed", "Fri"],
    nextAvailable: "2 days",
    location: "Clear Vision Eye Center",
    price: 180,
  },
  {
    id: 9,
    name: "Dr. Sophia Martinez",
    specialty: "OB/GYN",
    image: "https://images.unsplash.com/photo-1651008376811-b90baee60c1f?q=80&w=2070&auto=format&fit=crop",
    rating: 4.9,
    reviews: 187,
    experience: "13+ years",
    education: "UCLA School of Medicine",
    about: "Dr. Martinez provides comprehensive women's health services including prenatal care, gynecological exams, and minimally invasive surgeries.",
    availability: ["Tue", "Wed", "Thu", "Sat"],
    nextAvailable: "Today",
    location: "Women's Wellness Pavilion",
    price: 160,
  },
  {
    id: 10,
    name: "Dr. David Wilson",
    specialty: "Gastroenterologist",
    image: "https://images.unsplash.com/photo-1612531385446-f7e6d131e1d0?q=80&w=2070&auto=format&fit=crop",
    rating: 4.8,
    reviews: 105,
    experience: "18+ years",
    education: "University of Pennsylvania School of Medicine",
    about: "Dr. Wilson specializes in digestive health, including treatment of IBS, GERD, and inflammatory bowel diseases.",
    availability: ["Mon", "Wed", "Thu", "Fri"],
    nextAvailable: "Tomorrow",
    location: "Digestive Health Institute",
    price: 195,
  },
];

export const specialties = [
  "Cardiology",
  "Dermatology",
  "Neurology",
  // ...other specialties
];

export const timeSlots = [
  "9:00 AM", "9:30 AM", "10:00 AM", "10:30 AM", "11:00 AM", "11:30 AM",
  // ...other time slots
];

export const insuranceProviders = [
  "Blue Cross Blue Shield",
  "UnitedHealthcare",
  "Aetna",
  // ...other providers
];